### ISSUE TITLE
Remove Default <F8> Mapping

### ISSUE THREAD

**Issue by j5shi** [tell-k/vim-autopep8#16]
Hi, I think it's better to remove the default <F8> mapping for:

1. Normally it's a convention to provide mappings that are unique to a certain plugin, <F8> is too common.
2. If <F8> has been mapped, it will be overwritten by vim-autopop8, which is undesired.
3. Provoding the API is enough, it's the user's business to decide which key to be mapped to.

**Comment by tell-k** [comment]
@js5shi

Firstly, I apologize for the delay in replying to you.

You're right, My plugin is well-behaved might be bad.
In the next version I think that it is trying to remove the X.

Thanks for your suggestion.
