### ISSUE TITLE
Command drops unsaved changes

### ISSUE THREAD

**Issue by marciomazza** [tell-k/vim-autopep8#20]
If you used the command (:Autopep8) before saving the editor simply drops unsaved changes and works on the last saved content.

**Comment by Arnoldnuo** [comment]
How to fix the issue?

**Comment by marciomazza** [comment]
Did this happen before my commit 52869e876fff86455b2a8362be835cd5271216ae?

The first thing that comes to mind is to save the changes before running the command. Or maybe do the operation in a temp file with a copy of the current content...
