### ISSUE TITLE
autopep8 E501

### ISSUE THREAD

**Issue by lanox** [tell-k/vim-autopep8#21]
error line to long (86 >79 characters) [E501]

if i press F8 all i get is this
<img width="788" alt="screen shot 2015-12-30 at 12 44 52 am" src="https://cloud.githubusercontent.com/assets/7599183/12035231/aae41eba-ae8e-11e5-8128-3a5a55f55372.png">

I have also added ```let g:autopep8_max_line_length=79``` but it made no difference.

**Comment by dexhunter** [comment]
@lanox Hi! What did you do to solve this problem?
