### ISSUE TITLE
Use autopep8 with "="

### ISSUE THREAD

**Issue by mmaret-geny** [tell-k/vim-autopep8#22]
The = character is used to indent in vim.  
So may be, you can add the following line in your plugin on in your documentation to have the = character working with pep8

" Indentation with =
autocmd BufRead,BufNewFile *.py set equalprg=autopep8\ -

**Comment by tell-k** [comment]
@mmaret-geny Sorry, too late my reply.

Thanks for your suggestion.
I've written this tips on the README.rst :) 

Thx
