### ISSUE TITLE
Make this the default vim indent plugin

### ISSUE THREAD

**Issue by memeplex** [tell-k/vim-autopep8#25]
https://github.com/vim/vim/issues/483#event-706918725

**Comment by tell-k** [comment]
@memeplex Sorry, too late my reply. 

I saw the issue.

But, this plugin expects the user to have Python and autopep8 installed.

Therefore, it is inappropriate as vim's standard indent plugin.
(It is bad that standard plugin does not work if there is no specific library)

For that purpose,  [vim-python-pep8-indent](https://github.com/Vimjas/vim-python-pep8-indent) is more appropriate.
thx

**Comment by tmccombs** [comment]
Was there ever an attempt to bring vim-python-pep8-indent into mainline vim?
