### ISSUE TITLE
Only reformat selection

### ISSUE THREAD

**Issue by spaceone** [tell-k/vim-autopep8#29]
Hello, is it possible to only apply autopep8 to a selection of specific lines?
I tried this but seems not working. This would be a really nice feature!
For example I have a lot of template files which are partly python and partly bash or plaintext so I can't apply autopep8 to the whole file.

**Comment by tobixx** [comment]
There is already an open PR for it : #28

**Comment by spaceone** [comment]
Ah, very nice! Thanks!
