### ISSUE TITLE
auto go to first line after :Autopep8 format file

### ISSUE THREAD

**Issue by shidenggui** [tell-k/vim-autopep8#30]
A few days ago I update vim-autopep8 to v1.1, and I find  after `:Autopep8 <CR>` cursor auto go to first line. But in previous version it not change position. 
How can i disable this feature?

**Comment by tell-k** [comment]
@shidenggui  Sorry. there is no setting to disable it. 
However, I'll fix it. Please wait for the next version.

**Comment by yanpozka** [comment]
I'm having the same issue, is there any progress with this issue ?
Thanks for this plugins is awesome !!

**Comment by hmngwy** [comment]
Is there a fix yet?

**Comment by tell-k** [comment]
@hmngwy 
> we can send a PR?
Yes,  I want your help!  Let's send PR to me.

**Comment by tell-k** [comment]
@shidenggui @yanpozka 

Sorry for the late fix.
I've fixed it, Please try new version.
