### ISSUE TITLE
Error running Autopep8

### ISSUE THREAD

**Issue by JackieTseng** [tell-k/vim-autopep8#31]
Hi, I have followed the guide and put the contents of this repository in my ~/.vim/bundle directory. However when I run `:Autopep8`, vim get the following error:
`E492: Not an editor command: Autopep8`
Has anyone met this problem?

**Comment by C8LUKA** [comment]
Have you ever install the required in README.rst?

**Comment by tell-k** [comment]
Close. there is no response.
