### ISSUE TITLE
autopep8 execution at file save with vim autoload

### ISSUE THREAD

**Issue by ahakanbaba** [tell-k/vim-autopep8#34]
Would you consider adding an automatic autopep8 call everytime a file is saved in vim ? 

[vim-go](https://github.com/fatih/vim-go) and [vim-jsonnet](https://github.com/google/vim-jsonnet) behave similarly and it results in a very efficient developer experience. 

Anytime someone saves a python file, vim will execute autopep8 with the specified parameters and overwrite the buffer, without changing the undo history of the user.  

This may be an opt-in or opt-out feature. It is enabled by default in vim-go and also in vim-jsonnet. I would recommend to enable it by default too. But if you prefer the behavior can be opt-in too.

**Comment by tell-k** [comment]
@ahakanbaba   

I've merged your PR(#35) and released version 1.2.0 
https://www.vim.org/scripts/script.php?script_id=4614

Thank you for your suggestion and contribution.
