### ISSUE TITLE
Problems installing

### ISSUE THREAD

**Issue by jpnadas** [tell-k/vim-autopep8#38]
Hi,

I am getting the error "Not an editor command: Autopep8 " when trying to run `:Autopep8 ` on nvim. I also get "Unknown function: Autopep8" when running `:call Autopep8()`.

running `:help autopep8` opens the help documentation normally in nvim.

I installed the plugin via dein by adding `dein#add('tell-k/vim-autopep8')` to my init.vim file and running `:call dein#install()`. I have other plugins which work fine via dein installation.

I have installed autopep8 and can run it normally via command line.

Alternatively I have tried cloning this repo into ~/.vim/bundle/, but I get the same error in both vim and nvim.

In vim I get an "Sorry, no help for autopep8" when running `:help autopep8`.

I am fairly new to vim, so I might be missing something trivial. Does anyone have an idea of what I am doing wrong?

Thanks.

**Comment by dcr309duan** [comment]
I have the same problem, anyone can help~

**Comment by gonzaloamadio** [comment]
I have installed with vim-plug , and also following instructions, but have this error:

```
Error detected while processing function Autopep8:
line   11:
File autopep8 not found. Please install it first.
```

Some help?

**Comment by tammarut** [comment]
Same problem.
Any help?

**Comment by jpnadas** [comment]
It has been a long time since I opened this and I since then I switched to other plugin managers and I no longer have the error, so I solved it before.

In any case, looking back, it looks like the problem is not having the program `autopep8` installed, not the plugin. To solve it, simply run `pip install --user autopep8` or if you want it globally, `sudo pip install autopep8`.
