### ISSUE TITLE
Vim-autopep8 doesn't work

### ISSUE THREAD

**Issue by Johan-Palacios** [tell-k/vim-autopep8#43]
I have this issue
![image](https://user-images.githubusercontent.com/77251405/122114875-0b8c1e80-cde1-11eb-85d8-954ba7876fcb.png)

Can you give me a solution?

**Comment by YuanfengZhang** [comment]
Same as me. I have tried several autopep8 plugins but have not found one work well yet.

**Comment by YuanfengZhang** [comment]
I  solved it by uninstalling this plugin, doing apt-get install autopep8 and installing this plugin again.
